<#
.SYNOPSIS
  Installs (or repairs) humemory's Windows production wiring.

.DESCRIPTION
  Everything here runs without elevation, which is the binding constraint on the
  machine this was written for: `schtasks /sc onlogon` is refused without admin
  rights, so logon start goes through a Startup-folder launcher instead.

  Two pieces:
    - Startup launcher  — starts the API (which hosts the maintenance loop) at
                          logon, hidden, with its output in data\logs\api.log.
    - Watchdog task     — every N minutes, restarts the API if /health stops
                          answering. Its action is wscript.exe, a windowless
                          host, so it never flashes a console window. A task
                          running `cmd` does, which is what this replaced.

  Safe to re-run: it overwrites the launcher and re-registers the task.

.EXAMPLE
  pwsh -File scripts\windows\install.ps1
  pwsh -File scripts\windows\install.ps1 -WatchdogMinutes 10
  pwsh -File scripts\windows\install.ps1 -Uninstall
#>

[CmdletBinding()]
param(
  [int] $WatchdogMinutes = 5,
  [switch] $Uninstall
)

$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$root      = Split-Path -Parent (Split-Path -Parent $scriptDir)
$startup   = [Environment]::GetFolderPath('Startup')
$launcher  = Join-Path $scriptDir 'humemory-api.vbs'
$watchdog  = Join-Path $scriptDir 'humemory-watchdog.vbs'
$startupVbs = Join-Path $startup 'humemory-api.vbs'
$taskName  = 'humemory-watchdog'

function Write-Step($message) { Write-Host "  $message" }

if ($Uninstall) {
  Write-Host "`nRemoving humemory wiring..." -ForegroundColor Cyan
  if (Test-Path $startupVbs) { Remove-Item $startupVbs -Force; Write-Step "removed $startupVbs" }
  else { Write-Step 'no startup launcher to remove' }

  & schtasks /delete /tn $taskName /f 2>&1 | Out-Null
  if ($LASTEXITCODE -eq 0) { Write-Step "unregistered scheduled task $taskName" }
  else { Write-Step "no scheduled task $taskName" }

  Write-Host "`nDone. The API is still running if it was: stop it by hand.`n"
  return
}

Write-Host "`nInstalling humemory wiring from $root" -ForegroundColor Cyan

foreach ($file in @($launcher, $watchdog)) {
  if (-not (Test-Path $file)) { throw "Missing $file — is the repo complete?" }
}

# The Startup folder takes a copy rather than a shortcut: a shortcut to a path
# inside a repo breaks the moment the repo moves, and fails silently at logon.
# The copy is a two-line shim that defers to the versioned script.
$shim = @"
' Generated by scripts\windows\install.ps1 — do not edit.
' Defers to the versioned launcher so the real logic stays in git.
CreateObject("WScript.Shell").Run "wscript.exe ""$launcher""", 0, False
"@
Set-Content -Path $startupVbs -Value $shim -Encoding ASCII
Write-Step "startup launcher -> $startupVbs"

# /sc minute is allowed without elevation; /sc onlogon is not.
$action = "wscript.exe `"$watchdog`""
& schtasks /create /tn $taskName /sc minute /mo $WatchdogMinutes /tr $action /f 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) { throw "Could not register the $taskName scheduled task (exit $LASTEXITCODE)." }
Write-Step "watchdog task -> every $WatchdogMinutes min, windowless (wscript)"

Write-Host "`nInstalled. Verify with:" -ForegroundColor Green
Write-Host "  schtasks /query /tn $taskName"
Write-Host "  bun run src/cli/index.ts maintenance status`n"
